// Public family/category metadata from https://fonts.google.com/metadata/fonts
// Downloaded 2026-09-14. No font binaries are included.
let knownFontCategories: [String: Category] = [
    "ABeeZee": .sans,
    "ADLaM Display": .display,
    "AR One Sans": .sans,
    "Abel": .sans,
    "Abhaya Libre": .serif,
    "Aboreto": .display,
    "Abril Fatface": .display,
    "Abyssinica SIL": .serif,
    "Aclonica": .sans,
    "Acme": .sans,
    "Actor": .sans,
    "Adamina": .serif,
    "Advent Pro": .sans,
    "Afacad": .sans,
    "Afacad Flux": .sans,
    "Agbalumo": .display,
    "Agdasima": .sans,
    "Agu Display": .display,
    "Aguafina Script": .script,
    "Akatab": .sans,
    "Akaya Kanadaka": .display,
    "Akaya Telivigala": .display,
    "Akronim": .display,
    "Akshar": .sans,
    "Akt": .sans,
    "Aladin": .display,
    "Alan Sans": .sans,
    "Alata": .sans,
    "Alatsi": .sans,
    "Albert Sans": .sans,
    "Aldrich": .sans,
    "Alef": .sans,
    "Alegreya": .serif,
    "Alegreya SC": .serif,
    "Alegreya Sans": .sans,
    "Alegreya Sans SC": .sans,
    "Aleo": .serif,
    "Alex Brush": .script,
    "Alexandria": .sans,
    "Alfa Slab One": .display,
    "Alice": .serif,
    "Alien Block": .display,
    "Alike": .serif,
    "Alike Angular": .serif,
    "Alkalami": .serif,
    "Alkatra": .display,
    "Allan": .display,
    "Allerta": .sans,
    "Allerta Stencil": .sans,
    "Allison": .script,
    "Allkin": .display,
    "Allura": .script,
    "Almarai": .sans,
    "Almendra": .serif,
    "Almendra Display": .display,
    "Almendra SC": .serif,
    "Alumni Sans": .sans,
    "Alumni Sans Collegiate One": .sans,
    "Alumni Sans Inline One": .display,
    "Alumni Sans Pinstripe": .sans,
    "Alumni Sans SC": .sans,
    "Alyamama": .serif,
    "Amarante": .display,
    "Amaranth": .sans,
    "Amarna": .sans,
    "Amatic SC": .script,
    "Amethysta": .serif,
    "Amiko": .sans,
    "Amiri": .serif,
    "Amiri Quran": .serif,
    "Amita": .script,
    "Anaheim": .sans,
    "Ancizar Sans": .sans,
    "Ancizar Serif": .serif,
    "Andada Pro": .serif,
    "Andika": .sans,
    "Anek Bangla": .sans,
    "Anek Devanagari": .sans,
    "Anek Gujarati": .sans,
    "Anek Gurmukhi": .sans,
    "Anek Kannada": .sans,
    "Anek Latin": .sans,
    "Anek Malayalam": .sans,
    "Anek Odia": .sans,
    "Anek Tamil": .sans,
    "Anek Telugu": .sans,
    "Angkor": .display,
    "Annapurna SIL": .serif,
    "Annie Use Your Telescope": .script,
    "Anonymous Pro": .mono,
    "Anta": .sans,
    "Antic": .sans,
    "Antic Didone": .serif,
    "Antic Slab": .serif,
    "Anton": .sans,
    "Anton SC": .sans,
    "Antonio": .sans,
    "Anuphan": .sans,
    "Anybody": .display,
    "Aoboshi One": .serif,
    "Arapey": .serif,
    "Arbutus": .serif,
    "Arbutus Slab": .serif,
    "Architects Daughter": .script,
    "Archivo": .sans,
    "Archivo Black": .sans,
    "Archivo Narrow": .sans,
    "Are You Serious": .script,
    "Aref Ruqaa": .serif,
    "Aref Ruqaa Ink": .serif,
    "Arima": .display,
    "Arimo": .sans,
    "Arizonia": .script,
    "Armata": .sans,
    "Arsenal": .sans,
    "Arsenal SC": .sans,
    "Artifika": .serif,
    "Arvo": .serif,
    "Arya": .sans,
    "Asap": .sans,
    "Asap Condensed": .sans,
    "Asap Sharp": .sans,
    "Asar": .serif,
    "Asimovian": .sans,
    "Asset": .display,
    "Assistant": .sans,
    "Asta Sans": .sans,
    "Astloch": .display,
    "Asul": .serif,
    "Athiti": .sans,
    "Atkinson Hyperlegible": .sans,
    "Atkinson Hyperlegible Mono": .sans,
    "Atkinson Hyperlegible Next": .sans,
    "Atma": .display,
    "Atomic Age": .display,
    "Aubrey": .display,
    "Audiowide": .display,
    "Autour One": .display,
    "Average": .serif,
    "Average Sans": .sans,
    "Averia Gruesa Libre": .display,
    "Averia Libre": .display,
    "Averia Sans Libre": .display,
    "Averia Serif Libre": .display,
    "Azeret Mono": .mono,
    "B612": .sans,
    "B612 Mono": .mono,
    "BBH Bartle": .sans,
    "BBH Bogle": .sans,
    "BBH Hegarty": .sans,
    "BIZ UDGothic": .sans,
    "BIZ UDMincho": .serif,
    "BIZ UDPGothic": .sans,
    "BIZ UDPMincho": .serif,
    "BJCree": .serif,
    "Babylonica": .script,
    "Bacasime Antique": .serif,
    "Bad Script": .script,
    "Badeen Display": .display,
    "Bagel Fat One": .display,
    "Bahiana": .display,
    "Bahianita": .display,
    "Bai Jamjuree": .sans,
    "Bakbak One": .display,
    "Ballet": .script,
    "Baloo 2": .display,
    "Baloo Bhai 2": .display,
    "Baloo Bhaijaan 2": .display,
    "Baloo Bhaina 2": .display,
    "Baloo Chettan 2": .display,
    "Baloo Da 2": .display,
    "Baloo Paaji 2": .display,
    "Baloo Tamma 2": .display,
    "Baloo Tammudu 2": .display,
    "Baloo Thambi 2": .display,
    "Balsamiq Sans": .display,
    "Balthazar": .serif,
    "Bangers": .display,
    "Barlow": .sans,
    "Barlow Condensed": .sans,
    "Barlow Semi Condensed": .sans,
    "Barriecito": .display,
    "Barrio": .display,
    "Basic": .sans,
    "Baskervville": .serif,
    "Baskervville SC": .serif,
    "Battambang": .display,
    "Baumans": .display,
    "Bayon": .sans,
    "Be Vietnam Pro": .sans,
    "Beau Rivage": .script,
    "Bebas Neue": .sans,
    "Beiruti": .sans,
    "Belanosima": .sans,
    "Belgrano": .serif,
    "Bellefair": .serif,
    "Belleza": .sans,
    "Bellota": .display,
    "Bellota Text": .display,
    "BenchNine": .sans,
    "Benne": .serif,
    "Bentham": .serif,
    "Berkshire Swash": .script,
    "Besley": .serif,
    "Betania Patmos": .script,
    "Betania Patmos GDL": .script,
    "Betania Patmos In": .script,
    "Betania Patmos In GDL": .script,
    "Beth Ellen": .script,
    "Bevan": .serif,
    "BhuTuka Expanded One": .serif,
    "Big Shoulders": .display,
    "Big Shoulders Inline": .display,
    "Big Shoulders Stencil": .display,
    "Bigelow Rules": .display,
    "Bigshot One": .display,
    "Bilbo": .script,
    "Bilbo Swash Caps": .script,
    "BioRhyme": .serif,
    "BioRhyme Expanded": .serif,
    "Birthstone": .script,
    "Birthstone Bounce": .script,
    "Biryani": .sans,
    "Bitcount": .display,
    "Bitcount Grid Double": .display,
    "Bitcount Grid Double Ink": .display,
    "Bitcount Grid Single": .display,
    "Bitcount Grid Single Ink": .display,
    "Bitcount Ink": .display,
    "Bitcount Prop Double": .display,
    "Bitcount Prop Double Ink": .display,
    "Bitcount Prop Single": .display,
    "Bitcount Prop Single Ink": .display,
    "Bitcount Single": .display,
    "Bitcount Single Ink": .display,
    "Bitter": .serif,
    "Black And White Picture": .display,
    "Black Han Sans": .sans,
    "Black Ops One": .display,
    "Blaka": .display,
    "Blaka Hollow": .display,
    "Blaka Ink": .display,
    "Blinker": .sans,
    "Bodoni Moda": .serif,
    "Bodoni Moda SC": .serif,
    "Bokor": .display,
    "Boldonse": .display,
    "Bona Nova": .serif,
    "Bona Nova SC": .serif,
    "Bonbon": .script,
    "Bonheur Royale": .script,
    "Boogaloo": .display,
    "Borel": .script,
    "Bowlby One": .display,
    "Bowlby One SC": .display,
    "Bpmf Huninn": .sans,
    "Bpmf Iansui": .script,
    "Bpmf Zihi Kai Std": .sans,
    "Braah One": .sans,
    "Brawler": .serif,
    "Bree Serif": .serif,
    "Bricolage Grotesque": .sans,
    "Bruno Ace": .display,
    "Bruno Ace SC": .display,
    "Brygada 1918": .serif,
    "Bubblegum Sans": .display,
    "Bubbler One": .sans,
    "Buda": .display,
    "Buenard": .serif,
    "Bungee": .display,
    "Bungee Hairline": .display,
    "Bungee Inline": .display,
    "Bungee Outline": .display,
    "Bungee Shade": .display,
    "Bungee Spice": .display,
    "Bungee Tint": .display,
    "Butcherman": .display,
    "Butterfly Kids": .script,
    "Bytesized": .sans,
    "Caacupe One": .display,
    "Cabin": .sans,
    "Cabin Condensed": .sans,
    "Cabin Sketch": .display,
    "Cactus Classical Serif": .serif,
    "Caesar Dressing": .display,
    "Cagliostro": .sans,
    "Cairo": .sans,
    "Cairo Play": .sans,
    "Cal Sans": .sans,
    "Caladea": .serif,
    "Calistoga": .display,
    "Calligraffitti": .script,
    "Cambay": .sans,
    "Cambo": .serif,
    "Candal": .sans,
    "Cantarell": .sans,
    "Cantata One": .serif,
    "Cantora One": .sans,
    "Caprasimo": .display,
    "Capriola": .sans,
    "Caramel": .script,
    "Carattere": .script,
    "Cardo": .serif,
    "Carlito": .sans,
    "Carme": .sans,
    "Carrois Gothic": .sans,
    "Carrois Gothic SC": .sans,
    "Carter One": .display,
    "Cascadia Code": .sans,
    "Cascadia Mono": .sans,
    "Castoro": .serif,
    "Castoro Titling": .display,
    "Catamaran": .sans,
    "Caudex": .serif,
    "Cause": .script,
    "Caveat": .script,
    "Caveat Brush": .script,
    "Cedarville Cursive": .script,
    "Ceviche One": .display,
    "Chakra Petch": .sans,
    "Changa": .sans,
    "Changa One": .display,
    "Chango": .display,
    "Charis SIL": .serif,
    "Charm": .script,
    "Charmonman": .script,
    "Chathura": .sans,
    "Chau Philomene One": .sans,
    "Chela One": .display,
    "Chelsea Market": .display,
    "Chenla": .display,
    "Cherish": .script,
    "Cherry Bomb One": .display,
    "Cherry Cream Soda": .display,
    "Cherry Swash": .display,
    "Chewy": .display,
    "Chicle": .display,
    "Chilanka": .script,
    "Chiron GoRound TC": .sans,
    "Chiron Hei HK": .sans,
    "Chiron Sung HK": .serif,
    "Chivo": .sans,
    "Chivo Mono": .mono,
    "Chocolate Classical Sans": .sans,
    "Chokokutai": .display,
    "Chonburi": .display,
    "Cinzel": .serif,
    "Cinzel Decorative": .display,
    "Clicker Script": .script,
    "Climate Crisis": .display,
    "Coda": .display,
    "Codystar": .display,
    "Coiny": .display,
    "Combo": .display,
    "Comfortaa": .display,
    "Comforter": .script,
    "Comforter Brush": .script,
    "Comic Neue": .script,
    "Comic Relief": .display,
    "Coming Soon": .script,
    "Comme": .sans,
    "Commissioner": .sans,
    "Concert One": .display,
    "Condiment": .script,
    "Content": .display,
    "Contrail One": .display,
    "Convergence": .sans,
    "Cookie": .script,
    "Copse": .serif,
    "Coral Pixels": .display,
    "Corben": .display,
    "Corinthia": .script,
    "Cormorant": .serif,
    "Cormorant Garamond": .serif,
    "Cormorant Infant": .serif,
    "Cormorant SC": .serif,
    "Cormorant Unicase": .serif,
    "Cormorant Upright": .serif,
    "Cossette Texte": .sans,
    "Cossette Titre": .sans,
    "Courgette": .script,
    "Courier Prime": .mono,
    "Cousine": .mono,
    "Coustard": .serif,
    "Covered By Your Grace": .script,
    "Crafty Girls": .script,
    "Creepster": .display,
    "Crete Round": .serif,
    "Crimson Pro": .serif,
    "Crimson Text": .serif,
    "Croissant One": .display,
    "Crushed": .display,
    "Cuprum": .sans,
    "Cute Font": .display,
    "Cutive": .serif,
    "Cutive Mono": .mono,
    "DM Mono": .mono,
    "DM Sans": .sans,
    "DM Serif Display": .serif,
    "DM Serif Text": .serif,
    "Dai Banna SIL": .serif,
    "Damion": .script,
    "Dancing Script": .script,
    "Danfo": .serif,
    "Dangrek": .display,
    "Darker Grotesque": .sans,
    "Darumadrop One": .display,
    "Datatype": .mono,
    "David Libre": .serif,
    "Dawning of a New Day": .script,
    "Days One": .sans,
    "Dekko": .script,
    "Dela Gothic One": .display,
    "Delicious Handrawn": .script,
    "Delius": .script,
    "Delius Swash Caps": .script,
    "Delius Unicase": .script,
    "Della Respira": .serif,
    "Denk One": .sans,
    "Devonshire": .script,
    "Dhurjati": .sans,
    "Didact Gothic": .sans,
    "Diphylleia": .serif,
    "Diplomata": .display,
    "Diplomata SC": .display,
    "Do Hyeon": .sans,
    "Dokdo": .display,
    "Domine": .serif,
    "Donegal One": .serif,
    "Dongle": .sans,
    "Doppio One": .sans,
    "Dorsa": .sans,
    "Dosis": .sans,
    "DotGothic16": .sans,
    "Doto": .sans,
    "Dr Sugiyama": .script,
    "Duru Sans": .sans,
    "DynaPuff": .display,
    "Dynalight": .display,
    "EB Garamond": .serif,
    "Eagle Lake": .script,
    "East Sea Dokdo": .script,
    "Eater": .display,
    "Economica": .sans,
    "Eczar": .serif,
    "Edu AU VIC WA NT Arrows": .script,
    "Edu AU VIC WA NT Dots": .script,
    "Edu AU VIC WA NT Guides": .script,
    "Edu AU VIC WA NT Hand": .script,
    "Edu AU VIC WA NT Pre": .script,
    "Edu NSW ACT Cursive": .script,
    "Edu NSW ACT Foundation": .script,
    "Edu NSW ACT Hand Pre": .script,
    "Edu QLD Beginner": .script,
    "Edu QLD Hand": .script,
    "Edu SA Beginner": .script,
    "Edu SA Hand": .script,
    "Edu TAS Beginner": .script,
    "Edu VIC WA NT Beginner": .script,
    "Edu VIC WA NT Hand": .script,
    "Edu VIC WA NT Hand Pre": .script,
    "El Messiri": .sans,
    "Electrolize": .sans,
    "Elms Sans": .sans,
    "Elsie": .display,
    "Elsie Swash Caps": .display,
    "Emblema One": .display,
    "Emilys Candy": .display,
    "Encode Sans": .sans,
    "Encode Sans Condensed": .sans,
    "Encode Sans Expanded": .sans,
    "Encode Sans SC": .sans,
    "Encode Sans Semi Condensed": .sans,
    "Encode Sans Semi Expanded": .sans,
    "Engagement": .script,
    "Englebert": .sans,
    "Enriqueta": .serif,
    "Ephesis": .script,
    "Epilogue": .sans,
    "Epunda Sans": .sans,
    "Epunda Slab": .serif,
    "Erica One": .display,
    "Esteban": .serif,
    "Estedad": .sans,
    "Estonia": .script,
    "Euphoria Script": .script,
    "Ewert": .display,
    "Exile": .display,
    "Exo": .sans,
    "Exo 2": .sans,
    "Expletus Sans": .display,
    "Explora": .script,
    "Faculty Glyphic": .sans,
    "Fahkwang": .sans,
    "Familjen Grotesk": .sans,
    "Fanwood Text": .serif,
    "Farro": .sans,
    "Farsan": .display,
    "Fascinate": .display,
    "Fascinate Inline": .display,
    "Faster One": .display,
    "Fasthand": .display,
    "Fauna One": .serif,
    "Faustina": .serif,
    "Federant": .display,
    "Federo": .sans,
    "Felipa": .script,
    "Fenix": .serif,
    "Festive": .script,
    "Figtree": .sans,
    "Finger Paint": .display,
    "Finlandica Headline": .sans,
    "Finlandica Text": .sans,
    "Fira Code": .mono,
    "Fira Mono": .mono,
    "Fira Sans": .sans,
    "Fira Sans Condensed": .sans,
    "Fira Sans Extra Condensed": .sans,
    "Fjalla One": .sans,
    "Fjord One": .serif,
    "Flamenco": .display,
    "Flavors": .display,
    "Fleur De Leah": .script,
    "Flow Block": .display,
    "Flow Circular": .display,
    "Flow Rounded": .display,
    "Foldit": .display,
    "Fondamento": .script,
    "Fontdiner Swanky": .display,
    "Forum": .display,
    "Fragment Mono": .mono,
    "Francois One": .sans,
    "Frank Ruhl Libre": .serif,
    "Fraunces": .serif,
    "Freckle Face": .display,
    "Fredericka the Great": .display,
    "Fredoka": .sans,
    "Freehand": .display,
    "Freeman": .display,
    "Fresca": .sans,
    "Frijole": .display,
    "Fruktur": .display,
    "Fugaz One": .display,
    "Fuggles": .script,
    "Funnel Display": .display,
    "Funnel Sans": .sans,
    "Fustat": .sans,
    "Fuzzy Bubbles": .script,
    "GFS Didot": .serif,
    "GFS Neohellenic": .sans,
    "Ga Maamli": .display,
    "Gabarito": .display,
    "Gabriela": .serif,
    "Gaegu": .script,
    "Gafata": .sans,
    "Gajraj One": .display,
    "Galada": .display,
    "Galdeano": .sans,
    "Galindo": .display,
    "Gamja Flower": .script,
    "Gantari": .sans,
    "Gasoek One": .sans,
    "Gayathri": .sans,
    "Geist": .sans,
    "Geist Mono": .mono,
    "Geist Pixel": .display,
    "Gelasio": .serif,
    "Gemunu Libre": .sans,
    "Genos": .sans,
    "Gentium Book Plus": .serif,
    "Gentium Plus": .serif,
    "Geo": .sans,
    "Geologica": .sans,
    "Geom": .sans,
    "Geomini": .sans,
    "Georama": .sans,
    "Geostar": .display,
    "Geostar Fill": .display,
    "Germania One": .display,
    "Gideon Roman": .display,
    "Gidole": .sans,
    "Gidugu": .sans,
    "Gilda Display": .serif,
    "Girassol": .display,
    "Give You Glory": .script,
    "Glass Antiqua": .display,
    "Glegoo": .serif,
    "Gloock": .serif,
    "Gloria Hallelujah": .script,
    "Glory": .sans,
    "Gluten": .display,
    "Goblin One": .display,
    "Gochi Hand": .script,
    "Goldman": .display,
    "Golos Text": .sans,
    "Google Sans": .sans,
    "Google Sans Code": .mono,
    "Google Sans Flex": .sans,
    "Gorditas": .display,
    "Gothic A1": .sans,
    "Gotu": .sans,
    "Goudy Bookletter 1911": .serif,
    "Gowun Batang": .serif,
    "Gowun Dodum": .sans,
    "Graduate": .serif,
    "Grand Hotel": .script,
    "Grandiflora One": .serif,
    "Grandstander": .display,
    "Grape Nuts": .script,
    "Gravitas One": .display,
    "Great Vibes": .script,
    "Grechen Fuemen": .script,
    "Grenze": .serif,
    "Grenze Gotisch": .display,
    "Grey Qo": .script,
    "Griffy": .display,
    "Gruppo": .sans,
    "Gudea": .sans,
    "Gugi": .display,
    "Gulzar": .serif,
    "Gupter": .serif,
    "Gurajada": .sans,
    "Gveret Levin": .script,
    "Gwendolyn": .script,
    "Habibi": .serif,
    "Hachi Maru Pop": .script,
    "Hahmlet": .serif,
    "Halant": .serif,
    "Hammersmith One": .sans,
    "Hanalei": .display,
    "Hanalei Fill": .display,
    "Handjet": .display,
    "Handlee": .script,
    "Hanken Grotesk": .sans,
    "Hanuman": .serif,
    "Happy Monkey": .display,
    "Harmattan": .sans,
    "Headland One": .serif,
    "Hedvig Letters Sans": .sans,
    "Hedvig Letters Serif": .serif,
    "Heebo": .sans,
    "Henny Penny": .display,
    "Hepta Slab": .serif,
    "Herr Von Muellerhoff": .script,
    "Hi Melody": .script,
    "Hibur Mono": .mono,
    "Hina Mincho": .serif,
    "Hind": .sans,
    "Hind Guntur": .sans,
    "Hind Madurai": .sans,
    "Hind Mysuru": .sans,
    "Hind Siliguri": .sans,
    "Hind Vadodara": .sans,
    "Holtwood One SC": .serif,
    "Homemade Apple": .script,
    "Homenaje": .sans,
    "Honk": .display,
    "Host Grotesk": .sans,
    "Hubballi": .sans,
    "Hubot Sans": .sans,
    "Huninn": .sans,
    "Hurricane": .script,
    "IBM Plex Mono": .mono,
    "IBM Plex Sans": .sans,
    "IBM Plex Sans Arabic": .sans,
    "IBM Plex Sans Condensed": .sans,
    "IBM Plex Sans Devanagari": .sans,
    "IBM Plex Sans Hebrew": .sans,
    "IBM Plex Sans JP": .sans,
    "IBM Plex Sans KR": .sans,
    "IBM Plex Sans Thai": .sans,
    "IBM Plex Sans Thai Looped": .sans,
    "IBM Plex Serif": .serif,
    "IM Fell DW Pica": .serif,
    "IM Fell DW Pica SC": .serif,
    "IM Fell Double Pica": .serif,
    "IM Fell Double Pica SC": .serif,
    "IM Fell English": .serif,
    "IM Fell English SC": .serif,
    "IM Fell French Canon": .serif,
    "IM Fell French Canon SC": .serif,
    "IM Fell Great Primer": .serif,
    "IM Fell Great Primer SC": .serif,
    "Iansui": .script,
    "Ibarra Real Nova": .serif,
    "Iceberg": .display,
    "Iceland": .display,
    "Idiqlat": .serif,
    "Imbue": .serif,
    "Imperial Script": .script,
    "Imprima": .sans,
    "Inclusive Sans": .sans,
    "Inconsolata": .mono,
    "Inder": .sans,
    "Indie Flower": .script,
    "Ingrid Darling": .script,
    "Inika": .serif,
    "Inknut Antiqua": .serif,
    "Inria Sans": .sans,
    "Inria Serif": .serif,
    "Inspiration": .script,
    "Instrument Sans": .sans,
    "Instrument Serif": .serif,
    "Intel One Mono": .mono,
    "Inter": .sans,
    "Inter Tight": .sans,
    "Iosevka Charon": .mono,
    "Iosevka Charon Mono": .mono,
    "Irish Grover": .display,
    "Island Moments": .script,
    "Istok Web": .sans,
    "Italiana": .sans,
    "Italianno": .script,
    "Itim": .script,
    "Jacquard 12": .display,
    "Jacquard 12 Charted": .display,
    "Jacquard 24": .display,
    "Jacquard 24 Charted": .display,
    "Jacquarda Bastarda 9": .display,
    "Jacquarda Bastarda 9 Charted": .display,
    "Jacques Francois": .serif,
    "Jacques Francois Shadow": .display,
    "Jaini": .display,
    "Jaini Purva": .display,
    "Jaldi": .sans,
    "Jaro": .sans,
    "Jersey 10": .display,
    "Jersey 10 Charted": .display,
    "Jersey 15": .display,
    "Jersey 15 Charted": .display,
    "Jersey 20": .display,
    "Jersey 20 Charted": .display,
    "Jersey 25": .display,
    "Jersey 25 Charted": .display,
    "JetBrains Mono": .mono,
    "Jim Nightshade": .script,
    "Joan": .serif,
    "Jockey One": .sans,
    "Jolly Lodger": .display,
    "Jomhuria": .display,
    "Jomolhari": .serif,
    "Josefin Sans": .sans,
    "Josefin Slab": .serif,
    "Jost": .sans,
    "Joti One": .display,
    "Jua": .sans,
    "Judson": .serif,
    "Julee": .script,
    "Julius Sans One": .sans,
    "Junge": .serif,
    "Jura": .sans,
    "Just Another Hand": .script,
    "Just Me Again Down Here": .script,
    "K2D": .sans,
    "Kablammo": .display,
    "Kadwa": .serif,
    "Kaisei Decol": .serif,
    "Kaisei HarunoUmi": .serif,
    "Kaisei Opti": .serif,
    "Kaisei Tokumin": .serif,
    "Kalam": .script,
    "Kalnia": .serif,
    "Kalnia Glaze": .display,
    "Kameron": .serif,
    "Kanchenjunga": .sans,
    "Kanit": .sans,
    "Kantumruy Pro": .sans,
    "Kapakana": .script,
    "Karantina": .display,
    "Karla": .sans,
    "Karla Tamil Inclined": .sans,
    "Karla Tamil Upright": .sans,
    "Karma": .serif,
    "Katibeh": .display,
    "Kaushan Script": .script,
    "Kavivanar": .script,
    "Kavoon": .display,
    "Kay Pho Du": .serif,
    "Kdam Thmor Pro": .sans,
    "Keania One": .display,
    "Kedebideri": .sans,
    "Kelly Slab": .display,
    "Kenia": .display,
    "Khand": .sans,
    "Khmer": .sans,
    "Khula": .sans,
    "Kings": .script,
    "Kirang Haerang": .display,
    "Kite One": .sans,
    "Kiwi Maru": .serif,
    "Klee One": .script,
    "Knewave": .display,
    "KoHo": .sans,
    "Kodchasan": .sans,
    "Kode Mono": .mono,
    "Koh Santepheap": .serif,
    "Kolker Brush": .script,
    "Konkhmer Sleokchher": .display,
    "Kosugi": .sans,
    "Kosugi Maru": .sans,
    "Kotta One": .serif,
    "Koulen": .display,
    "Kranky": .display,
    "Kreon": .serif,
    "Kristi": .script,
    "Krona One": .sans,
    "Krub": .sans,
    "Kufam": .sans,
    "Kulim Park": .sans,
    "Kumar One": .display,
    "Kumar One Outline": .display,
    "Kumbh Sans": .sans,
    "Kurale": .serif,
    "LINE Seed JP": .sans,
    "LXGW Marker Gothic": .sans,
    "LXGW WenKai Mono TC": .mono,
    "LXGW WenKai TC": .script,
    "La Belle Aurore": .script,
    "Labrada": .serif,
    "Lacquer": .display,
    "Laila": .serif,
    "Lakki Reddy": .script,
    "Lalezar": .sans,
    "Lancelot": .display,
    "Langar": .display,
    "Lateef": .serif,
    "Lato": .sans,
    "Lavishly Yours": .script,
    "League Gothic": .sans,
    "League Script": .script,
    "League Spartan": .sans,
    "Leckerli One": .script,
    "Ledger": .serif,
    "Lekton": .mono,
    "Lemon": .display,
    "Lemonada": .display,
    "Lexend": .sans,
    "Lexend Deca": .sans,
    "Lexend Exa": .sans,
    "Lexend Giga": .sans,
    "Lexend Mega": .sans,
    "Lexend Peta": .sans,
    "Lexend Tera": .sans,
    "Lexend Zetta": .sans,
    "Libertinus Keyboard": .display,
    "Libertinus Math": .display,
    "Libertinus Mono": .mono,
    "Libertinus Sans": .sans,
    "Libertinus Serif": .serif,
    "Libertinus Serif Display": .display,
    "Libre Barcode 128": .display,
    "Libre Barcode 128 Text": .display,
    "Libre Barcode 39": .display,
    "Libre Barcode 39 Extended": .display,
    "Libre Barcode 39 Extended Text": .display,
    "Libre Barcode 39 Text": .display,
    "Libre Barcode EAN13 Text": .display,
    "Libre Baskerville": .serif,
    "Libre Bodoni": .serif,
    "Libre Caslon Display": .serif,
    "Libre Caslon Text": .serif,
    "Libre Franklin": .sans,
    "Licorice": .script,
    "Life Savers": .display,
    "Lilex": .mono,
    "Lilita One": .display,
    "Lily Script One": .display,
    "Limelight": .display,
    "Linden Hill": .serif,
    "Linefont": .display,
    "Lisu Bosa": .serif,
    "Liter": .sans,
    "Literata": .serif,
    "Liu Jian Mao Cao": .script,
    "Livvic": .sans,
    "Lobster": .display,
    "Lobster Two": .display,
    "Londrina Outline": .display,
    "Londrina Shadow": .display,
    "Londrina Sketch": .display,
    "Londrina Solid": .display,
    "Long Cang": .script,
    "Lora": .serif,
    "Love Light": .script,
    "Love Ya Like A Sister": .display,
    "Loved by the King": .script,
    "Lovers Quarrel": .script,
    "Luckiest Guy": .display,
    "Lugrasimo": .script,
    "Lumanosimo": .script,
    "Lunasima": .sans,
    "Lusitana": .serif,
    "Lustria": .serif,
    "Luxurious Roman": .display,
    "Luxurious Script": .script,
    "M PLUS 1": .sans,
    "M PLUS 1 Code": .mono,
    "M PLUS 1p": .sans,
    "M PLUS 2": .sans,
    "M PLUS Code Latin": .sans,
    "M PLUS Rounded 1c": .sans,
    "M PLUS U": .sans,
    "Ma Shan Zheng": .script,
    "Macondo": .display,
    "Macondo Swash Caps": .display,
    "Mada": .sans,
    "Madimi One": .sans,
    "Magra": .sans,
    "Maiden Orange": .serif,
    "Maitree": .serif,
    "Major Mono Display": .mono,
    "Mako": .sans,
    "Mali": .script,
    "Mallanna": .sans,
    "Maname": .serif,
    "Mandali": .sans,
    "Manjari": .sans,
    "Manrope": .sans,
    "Mansalva": .script,
    "Manuale": .serif,
    "Manufacturing Consent": .display,
    "Marcellus": .serif,
    "Marcellus SC": .serif,
    "Marck Script": .script,
    "Margarine": .display,
    "Marhey": .display,
    "Markazi Text": .serif,
    "Marko One": .serif,
    "Marmelad": .sans,
    "Martel": .serif,
    "Martel Sans": .sans,
    "Martian Mono": .mono,
    "Marvel": .sans,
    "Matangi": .sans,
    "Mate": .serif,
    "Mate SC": .serif,
    "Matemasie": .sans,
    "Maven Pro": .sans,
    "McLaren": .display,
    "Mea Culpa": .script,
    "Meddon": .script,
    "MedievalSharp": .display,
    "Medula One": .display,
    "Meera Inimai": .sans,
    "Megrim": .display,
    "Meie Script": .script,
    "Menbere": .sans,
    "Meow Script": .script,
    "Merienda": .script,
    "Merriweather": .serif,
    "Merriweather Sans": .sans,
    "Metal": .display,
    "Metal Mania": .display,
    "Metamorphous": .display,
    "Metrophobic": .sans,
    "Michroma": .sans,
    "Micro 5": .display,
    "Micro 5 Charted": .display,
    "Milonga": .display,
    "Miltonian": .display,
    "Miltonian Tattoo": .display,
    "Mina": .sans,
    "Mingzat": .sans,
    "Miniver": .display,
    "Miranda Sans": .sans,
    "Miriam Libre": .sans,
    "Mirza": .serif,
    "Miss Fajardose": .script,
    "Mitr": .sans,
    "Mochiy Pop One": .sans,
    "Mochiy Pop P One": .sans,
    "Modak": .display,
    "Modern Antiqua": .display,
    "Moderustic": .sans,
    "Mogra": .display,
    "Mohave": .sans,
    "Moirai One": .display,
    "Molengo": .sans,
    "Molle": .script,
    "Momo Signature": .sans,
    "Momo Trust Display": .sans,
    "Momo Trust Sans": .sans,
    "Mona Sans": .sans,
    "Monda": .sans,
    "Monofett": .mono,
    "Monomakh": .display,
    "Monomaniac One": .sans,
    "Monoton": .display,
    "Monsieur La Doulaise": .script,
    "Montaga": .serif,
    "Montagu Slab": .serif,
    "MonteCarlo": .script,
    "Montenegrin Gothic One": .serif,
    "Montez": .script,
    "Montserrat": .sans,
    "Montserrat Alternates": .sans,
    "Montserrat Underline": .sans,
    "Moo Lah Lah": .display,
    "Mooli": .sans,
    "Moon Dance": .script,
    "Moul": .display,
    "Moulpali": .sans,
    "Mountains of Christmas": .display,
    "Mouse Memoirs": .sans,
    "Mozilla Headline": .sans,
    "Mozilla Text": .sans,
    "Mr Bedfort": .script,
    "Mr Dafoe": .script,
    "Mr De Haviland": .script,
    "Mrs Saint Delafield": .script,
    "Mrs Sheppards": .script,
    "Ms Madi": .script,
    "Mukta": .sans,
    "Mukta Mahee": .sans,
    "Mukta Malar": .sans,
    "Mukta Vaani": .sans,
    "Mulish": .sans,
    "Murecho": .sans,
    "MuseoModerno": .display,
    "My Soul": .script,
    "Mynerve": .script,
    "Mystery Quest": .display,
    "NTR": .sans,
    "Nabla": .display,
    "Namdhinggo": .serif,
    "Nanum Brush Script": .script,
    "Nanum Gothic": .sans,
    "Nanum Gothic Coding": .script,
    "Nanum Myeongjo": .serif,
    "Nanum Pen Script": .script,
    "Narnoor": .sans,
    "Nata Sans": .sans,
    "National Park": .sans,
    "Neonderthaw": .script,
    "Nerko One": .script,
    "Neucha": .script,
    "Neuton": .serif,
    "New Amsterdam": .sans,
    "New Rocker": .display,
    "New Tegomin": .serif,
    "News Cycle": .sans,
    "Newsreader": .serif,
    "Niconne": .script,
    "Niramit": .sans,
    "Nixie One": .display,
    "Nobile": .sans,
    "Nokora": .sans,
    "Norican": .script,
    "Nosifer": .display,
    "Notable": .sans,
    "Nothing You Could Do": .script,
    "Noticia Text": .serif,
    "Noto Color Emoji": .sans,
    "Noto Emoji": .sans,
    "Noto Kufi Arabic": .sans,
    "Noto Music": .sans,
    "Noto Naskh Arabic": .serif,
    "Noto Nastaliq Urdu": .serif,
    "Noto Rashi Hebrew": .serif,
    "Noto Sans": .sans,
    "Noto Sans Adlam": .sans,
    "Noto Sans Adlam Unjoined": .sans,
    "Noto Sans Anatolian Hieroglyphs": .sans,
    "Noto Sans Arabic": .sans,
    "Noto Sans Armenian": .sans,
    "Noto Sans Avestan": .sans,
    "Noto Sans Balinese": .sans,
    "Noto Sans Bamum": .sans,
    "Noto Sans Bassa Vah": .sans,
    "Noto Sans Batak": .sans,
    "Noto Sans Bengali": .sans,
    "Noto Sans Bhaiksuki": .sans,
    "Noto Sans Brahmi": .sans,
    "Noto Sans Buginese": .sans,
    "Noto Sans Buhid": .sans,
    "Noto Sans Canadian Aboriginal": .sans,
    "Noto Sans Carian": .sans,
    "Noto Sans Caucasian Albanian": .sans,
    "Noto Sans Chakma": .sans,
    "Noto Sans Cham": .sans,
    "Noto Sans Cherokee": .sans,
    "Noto Sans Chorasmian": .sans,
    "Noto Sans Coptic": .sans,
    "Noto Sans Cuneiform": .sans,
    "Noto Sans Cypriot": .sans,
    "Noto Sans Cypro Minoan": .sans,
    "Noto Sans Deseret": .sans,
    "Noto Sans Devanagari": .sans,
    "Noto Sans Display": .sans,
    "Noto Sans Duployan": .sans,
    "Noto Sans Egyptian Hieroglyphs": .sans,
    "Noto Sans Elbasan": .sans,
    "Noto Sans Elymaic": .sans,
    "Noto Sans Ethiopic": .sans,
    "Noto Sans Georgian": .sans,
    "Noto Sans Glagolitic": .sans,
    "Noto Sans Gothic": .sans,
    "Noto Sans Grantha": .sans,
    "Noto Sans Gujarati": .sans,
    "Noto Sans Gunjala Gondi": .sans,
    "Noto Sans Gurmukhi": .sans,
    "Noto Sans HK": .sans,
    "Noto Sans Hanifi Rohingya": .sans,
    "Noto Sans Hanunoo": .sans,
    "Noto Sans Hatran": .sans,
    "Noto Sans Hebrew": .sans,
    "Noto Sans Imperial Aramaic": .sans,
    "Noto Sans Indic Siyaq Numbers": .sans,
    "Noto Sans Inscriptional Pahlavi": .sans,
    "Noto Sans Inscriptional Parthian": .sans,
    "Noto Sans JP": .sans,
    "Noto Sans Javanese": .sans,
    "Noto Sans KR": .sans,
    "Noto Sans Kaithi": .sans,
    "Noto Sans Kannada": .sans,
    "Noto Sans Kawi": .sans,
    "Noto Sans Kayah Li": .sans,
    "Noto Sans Kharoshthi": .sans,
    "Noto Sans Khmer": .sans,
    "Noto Sans Khojki": .sans,
    "Noto Sans Khudawadi": .sans,
    "Noto Sans Lao": .sans,
    "Noto Sans Lao Looped": .sans,
    "Noto Sans Lepcha": .sans,
    "Noto Sans Limbu": .sans,
    "Noto Sans Linear A": .sans,
    "Noto Sans Linear B": .sans,
    "Noto Sans Lisu": .sans,
    "Noto Sans Lycian": .sans,
    "Noto Sans Lydian": .sans,
    "Noto Sans Mahajani": .sans,
    "Noto Sans Malayalam": .sans,
    "Noto Sans Mandaic": .sans,
    "Noto Sans Manichaean": .sans,
    "Noto Sans Marchen": .sans,
    "Noto Sans Masaram Gondi": .sans,
    "Noto Sans Math": .sans,
    "Noto Sans Mayan Numerals": .sans,
    "Noto Sans Medefaidrin": .sans,
    "Noto Sans Meetei Mayek": .sans,
    "Noto Sans Mende Kikakui": .sans,
    "Noto Sans Meroitic": .sans,
    "Noto Sans Miao": .sans,
    "Noto Sans Modi": .sans,
    "Noto Sans Mongolian": .sans,
    "Noto Sans Mono": .sans,
    "Noto Sans Mro": .sans,
    "Noto Sans Multani": .sans,
    "Noto Sans Myanmar": .sans,
    "Noto Sans NKo": .sans,
    "Noto Sans NKo Unjoined": .sans,
    "Noto Sans Nabataean": .sans,
    "Noto Sans Nag Mundari": .sans,
    "Noto Sans Nandinagari": .sans,
    "Noto Sans New Tai Lue": .sans,
    "Noto Sans Newa": .sans,
    "Noto Sans Nushu": .sans,
    "Noto Sans Ogham": .sans,
    "Noto Sans Ol Chiki": .sans,
    "Noto Sans Old Hungarian": .sans,
    "Noto Sans Old Italic": .sans,
    "Noto Sans Old North Arabian": .sans,
    "Noto Sans Old Permic": .sans,
    "Noto Sans Old Persian": .sans,
    "Noto Sans Old Sogdian": .sans,
    "Noto Sans Old South Arabian": .sans,
    "Noto Sans Old Turkic": .sans,
    "Noto Sans Oriya": .sans,
    "Noto Sans Osage": .sans,
    "Noto Sans Osmanya": .sans,
    "Noto Sans Pahawh Hmong": .sans,
    "Noto Sans Palmyrene": .sans,
    "Noto Sans Pau Cin Hau": .sans,
    "Noto Sans PhagsPa": .sans,
    "Noto Sans Phoenician": .sans,
    "Noto Sans Psalter Pahlavi": .sans,
    "Noto Sans Rejang": .sans,
    "Noto Sans Runic": .sans,
    "Noto Sans SC": .sans,
    "Noto Sans Samaritan": .sans,
    "Noto Sans Saurashtra": .sans,
    "Noto Sans Sharada": .sans,
    "Noto Sans Shavian": .sans,
    "Noto Sans Siddham": .sans,
    "Noto Sans SignWriting": .sans,
    "Noto Sans Sinhala": .sans,
    "Noto Sans Sogdian": .sans,
    "Noto Sans Sora Sompeng": .sans,
    "Noto Sans Soyombo": .sans,
    "Noto Sans Sundanese": .sans,
    "Noto Sans Sunuwar": .sans,
    "Noto Sans Syloti Nagri": .sans,
    "Noto Sans Symbols": .sans,
    "Noto Sans Symbols 2": .sans,
    "Noto Sans Syriac": .sans,
    "Noto Sans Syriac Eastern": .sans,
    "Noto Sans Syriac Western": .sans,
    "Noto Sans TC": .sans,
    "Noto Sans Tagalog": .sans,
    "Noto Sans Tagbanwa": .sans,
    "Noto Sans Tai Le": .sans,
    "Noto Sans Tai Tham": .sans,
    "Noto Sans Tai Viet": .sans,
    "Noto Sans Takri": .sans,
    "Noto Sans Tamil": .sans,
    "Noto Sans Tamil Supplement": .sans,
    "Noto Sans Tangsa": .sans,
    "Noto Sans Telugu": .sans,
    "Noto Sans Thaana": .sans,
    "Noto Sans Thai": .sans,
    "Noto Sans Thai Looped": .sans,
    "Noto Sans Tifinagh": .sans,
    "Noto Sans Tirhuta": .sans,
    "Noto Sans Ugaritic": .sans,
    "Noto Sans Vai": .sans,
    "Noto Sans Vithkuqi": .sans,
    "Noto Sans Wancho": .sans,
    "Noto Sans Warang Citi": .sans,
    "Noto Sans Yi": .sans,
    "Noto Sans Zanabazar Square": .sans,
    "Noto Serif": .serif,
    "Noto Serif Ahom": .serif,
    "Noto Serif Armenian": .serif,
    "Noto Serif Balinese": .serif,
    "Noto Serif Bengali": .serif,
    "Noto Serif Devanagari": .serif,
    "Noto Serif Display": .serif,
    "Noto Serif Dives Akuru": .serif,
    "Noto Serif Dogra": .serif,
    "Noto Serif Ethiopic": .serif,
    "Noto Serif Georgian": .serif,
    "Noto Serif Grantha": .serif,
    "Noto Serif Gujarati": .serif,
    "Noto Serif Gurmukhi": .serif,
    "Noto Serif HK": .serif,
    "Noto Serif Hebrew": .serif,
    "Noto Serif Hentaigana": .serif,
    "Noto Serif JP": .serif,
    "Noto Serif KR": .serif,
    "Noto Serif Kannada": .serif,
    "Noto Serif Khitan Small Script": .serif,
    "Noto Serif Khmer": .serif,
    "Noto Serif Khojki": .serif,
    "Noto Serif Lao": .serif,
    "Noto Serif Makasar": .serif,
    "Noto Serif Malayalam": .serif,
    "Noto Serif Myanmar": .serif,
    "Noto Serif NP Hmong": .serif,
    "Noto Serif Old Uyghur": .serif,
    "Noto Serif Oriya": .serif,
    "Noto Serif Ottoman Siyaq": .serif,
    "Noto Serif SC": .serif,
    "Noto Serif Sinhala": .serif,
    "Noto Serif TC": .serif,
    "Noto Serif Tamil": .serif,
    "Noto Serif Tangut": .serif,
    "Noto Serif Telugu": .serif,
    "Noto Serif Thai": .serif,
    "Noto Serif Tibetan": .serif,
    "Noto Serif Todhri": .serif,
    "Noto Serif Toto": .serif,
    "Noto Serif Vithkuqi": .serif,
    "Noto Serif Yezidi": .serif,
    "Noto Traditional Nushu": .sans,
    "Noto Znamenny Musical Notation": .sans,
    "Nova Cut": .display,
    "Nova Flat": .display,
    "Nova Mono": .mono,
    "Nova Oval": .display,
    "Nova Round": .display,
    "Nova Script": .display,
    "Nova Slim": .display,
    "Nova Square": .display,
    "Numans": .sans,
    "Nunito": .sans,
    "Nunito Sans": .sans,
    "Nuosu SIL": .sans,
    "Odibee Sans": .display,
    "Odor Mean Chey": .serif,
    "Offside": .display,
    "Oi": .display,
    "Ojuju": .sans,
    "Old Standard TT": .serif,
    "Oldenburg": .display,
    "Ole": .script,
    "Oleo Script": .display,
    "Oleo Script Swash Caps": .display,
    "Onest": .sans,
    "Oooh Baby": .script,
    "Open Sans": .sans,
    "Oranienbaum": .serif,
    "Orbit": .sans,
    "Orbitron": .sans,
    "Oregano": .display,
    "Orelega One": .display,
    "Orienta": .sans,
    "Original Surfer": .display,
    "Oswald": .sans,
    "Outfit": .sans,
    "Over the Rainbow": .script,
    "Overlock": .display,
    "Overlock SC": .display,
    "Overpass": .sans,
    "Overpass Mono": .mono,
    "Ovo": .serif,
    "Oxanium": .display,
    "Oxygen": .sans,
    "Oxygen Mono": .mono,
    "PT Mono": .mono,
    "PT Sans": .sans,
    "PT Sans Caption": .sans,
    "PT Sans Narrow": .sans,
    "PT Serif": .serif,
    "PT Serif Caption": .serif,
    "Pacifico": .script,
    "Padauk": .sans,
    "Padyakke Expanded One": .serif,
    "Palanquin": .sans,
    "Palanquin Dark": .sans,
    "Palette Mosaic": .display,
    "Pangolin": .script,
    "Paprika": .display,
    "Parastoo": .serif,
    "Parisienne": .script,
    "Parkinsans": .sans,
    "Passero One": .display,
    "Passion One": .display,
    "Passions Conflict": .script,
    "Pathway Extreme": .sans,
    "Pathway Gothic One": .sans,
    "Patrick Hand": .script,
    "Patrick Hand SC": .script,
    "Pattaya": .sans,
    "Patua One": .display,
    "Pavanam": .sans,
    "Paytone One": .sans,
    "Peddana": .serif,
    "Peralta": .serif,
    "Permanent Marker": .script,
    "Petemoss": .script,
    "Petit Formal Script": .script,
    "Petrona": .serif,
    "Phetsarath": .sans,
    "Philosopher": .sans,
    "Phudu": .display,
    "Piazzolla": .serif,
    "Piedra": .display,
    "Pinyon Script": .script,
    "Pirata One": .display,
    "Pixelify Sans": .display,
    "Plaster": .display,
    "Platypi": .serif,
    "Play": .sans,
    "Playball": .display,
    "Playfair": .serif,
    "Playfair Display": .serif,
    "Playfair Display SC": .serif,
    "Playpen Sans": .script,
    "Playpen Sans Arabic": .script,
    "Playpen Sans Deva": .script,
    "Playpen Sans Hebrew": .script,
    "Playpen Sans Thai": .script,
    "Playwrite AR": .script,
    "Playwrite AR Guides": .script,
    "Playwrite AT": .script,
    "Playwrite AT Guides": .script,
    "Playwrite AU NSW": .script,
    "Playwrite AU NSW Guides": .script,
    "Playwrite AU QLD": .script,
    "Playwrite AU QLD Guides": .script,
    "Playwrite AU SA": .script,
    "Playwrite AU SA Guides": .script,
    "Playwrite AU TAS": .script,
    "Playwrite AU TAS Guides": .script,
    "Playwrite AU VIC": .script,
    "Playwrite AU VIC Guides": .script,
    "Playwrite BE VLG": .script,
    "Playwrite BE VLG Guides": .script,
    "Playwrite BE WAL": .script,
    "Playwrite BE WAL Guides": .script,
    "Playwrite BR": .script,
    "Playwrite BR Guides": .script,
    "Playwrite CA": .script,
    "Playwrite CA Guides": .script,
    "Playwrite CL": .script,
    "Playwrite CL Guides": .script,
    "Playwrite CO": .script,
    "Playwrite CO Guides": .script,
    "Playwrite CU": .script,
    "Playwrite CU Guides": .script,
    "Playwrite CZ": .script,
    "Playwrite CZ Guides": .script,
    "Playwrite DE Grund": .script,
    "Playwrite DE Grund Guides": .script,
    "Playwrite DE LA": .script,
    "Playwrite DE LA Guides": .script,
    "Playwrite DE SAS": .script,
    "Playwrite DE SAS Guides": .script,
    "Playwrite DE VA": .script,
    "Playwrite DE VA Guides": .script,
    "Playwrite DK Loopet": .script,
    "Playwrite DK Loopet Guides": .script,
    "Playwrite DK Uloopet": .script,
    "Playwrite DK Uloopet Guides": .script,
    "Playwrite ES": .script,
    "Playwrite ES Deco": .script,
    "Playwrite ES Deco Guides": .script,
    "Playwrite ES Guides": .script,
    "Playwrite FR Moderne": .script,
    "Playwrite FR Moderne Guides": .script,
    "Playwrite FR Trad": .script,
    "Playwrite FR Trad Guides": .script,
    "Playwrite GB J": .script,
    "Playwrite GB J Guides": .script,
    "Playwrite GB S": .script,
    "Playwrite GB S Guides": .script,
    "Playwrite HR": .script,
    "Playwrite HR Guides": .script,
    "Playwrite HR Lijeva": .script,
    "Playwrite HR Lijeva Guides": .script,
    "Playwrite HU": .script,
    "Playwrite HU Guides": .script,
    "Playwrite ID": .script,
    "Playwrite ID Guides": .script,
    "Playwrite IE": .script,
    "Playwrite IE Guides": .script,
    "Playwrite IN": .script,
    "Playwrite IN Guides": .script,
    "Playwrite IS": .script,
    "Playwrite IS Guides": .script,
    "Playwrite IT Moderna": .script,
    "Playwrite IT Moderna Guides": .script,
    "Playwrite IT Trad": .script,
    "Playwrite IT Trad Guides": .script,
    "Playwrite MX": .script,
    "Playwrite MX Guides": .script,
    "Playwrite NG Modern": .script,
    "Playwrite NG Modern Guides": .script,
    "Playwrite NL": .script,
    "Playwrite NL Guides": .script,
    "Playwrite NO": .script,
    "Playwrite NO Guides": .script,
    "Playwrite NZ": .script,
    "Playwrite NZ Basic": .script,
    "Playwrite NZ Basic Guides": .script,
    "Playwrite NZ Guides": .script,
    "Playwrite PE": .script,
    "Playwrite PE Guides": .script,
    "Playwrite PL": .script,
    "Playwrite PL Guides": .script,
    "Playwrite PT": .script,
    "Playwrite PT Guides": .script,
    "Playwrite RO": .script,
    "Playwrite RO Guides": .script,
    "Playwrite SK": .script,
    "Playwrite SK Guides": .script,
    "Playwrite TZ": .script,
    "Playwrite TZ Guides": .script,
    "Playwrite US Modern": .script,
    "Playwrite US Modern Guides": .script,
    "Playwrite US Trad": .script,
    "Playwrite US Trad Guides": .script,
    "Playwrite VN": .script,
    "Playwrite VN Guides": .script,
    "Playwrite ZA": .script,
    "Playwrite ZA Guides": .script,
    "Pliant": .sans,
    "Plus Jakarta Sans": .sans,
    "Pochaevsk": .display,
    "Podkova": .serif,
    "Poetsen One": .display,
    "Poiret One": .display,
    "Poller One": .display,
    "Poltawski Nowy": .serif,
    "Poly": .serif,
    "Pompiere": .display,
    "Ponnala": .display,
    "Ponomar": .display,
    "Pontano Sans": .sans,
    "Poor Story": .display,
    "Poppins": .sans,
    "Port Lligat Sans": .sans,
    "Port Lligat Slab": .serif,
    "Potta One": .display,
    "Pragati Narrow": .sans,
    "Praise": .script,
    "Prata": .serif,
    "Preahvihear": .sans,
    "Press Start 2P": .display,
    "Pridi": .serif,
    "Princess Sofia": .script,
    "Prociono": .serif,
    "Prompt": .sans,
    "Prosto One": .display,
    "Protest Guerrilla": .display,
    "Protest Revolution": .display,
    "Protest Riot": .display,
    "Protest Strike": .display,
    "Proza Libre": .sans,
    "Public Sans": .sans,
    "Puppies Play": .script,
    "Puritan": .sans,
    "Purple Purse": .display,
    "Qahiri": .sans,
    "Quando": .serif,
    "Quantico": .sans,
    "Quattrocento": .serif,
    "Quattrocento Sans": .sans,
    "Questrial": .sans,
    "Quicksand": .sans,
    "Quintessential": .script,
    "Qwigley": .script,
    "Qwitcher Grypen": .script,
    "REM": .sans,
    "Racing Sans One": .display,
    "Radio Canada": .sans,
    "Radio Canada Big": .sans,
    "Radley": .serif,
    "Rajdhani": .sans,
    "Rakkas": .display,
    "Raleway": .sans,
    "Raleway Dots": .display,
    "Ramabhadra": .sans,
    "Ramaraja": .serif,
    "Rambla": .sans,
    "Rammetto One": .display,
    "Rampart One": .display,
    "Ramsina": .serif,
    "Ranchers": .display,
    "Rancho": .script,
    "Ranga": .display,
    "Rasa": .serif,
    "Rationale": .sans,
    "Ravi Prakash": .display,
    "Readex Pro": .sans,
    "Recursive": .sans,
    "Red Hat Display": .sans,
    "Red Hat Mono": .mono,
    "Red Hat Text": .sans,
    "Red Rose": .display,
    "Redacted": .display,
    "Redacted Script": .display,
    "Reddit Mono": .mono,
    "Reddit Sans": .sans,
    "Reddit Sans Condensed": .sans,
    "Redressed": .script,
    "Reem Kufi": .sans,
    "Reem Kufi Fun": .sans,
    "Reem Kufi Ink": .sans,
    "Reenie Beanie": .script,
    "Reggae One": .display,
    "Rethink Sans": .sans,
    "Revalia": .display,
    "Rhodium Libre": .serif,
    "Ribeye": .display,
    "Ribeye Marrow": .display,
    "Righteous": .display,
    "Risque": .display,
    "Road Rage": .display,
    "Roboto": .sans,
    "Roboto Condensed": .sans,
    "Roboto Flex": .sans,
    "Roboto Mono": .mono,
    "Roboto Serif": .serif,
    "Roboto Slab": .serif,
    "Rochester": .script,
    "Rock 3D": .display,
    "Rock Salt": .script,
    "RocknRoll One": .sans,
    "Rokkitt": .serif,
    "Romanesco": .script,
    "Ropa Sans": .sans,
    "Rosario": .sans,
    "Rosarivo": .serif,
    "Rouge Script": .script,
    "Rowdies": .display,
    "Rozha One": .serif,
    "Rubik": .sans,
    "Rubik 80s Fade": .display,
    "Rubik Beastly": .display,
    "Rubik Broken Fax": .display,
    "Rubik Bubbles": .display,
    "Rubik Burned": .display,
    "Rubik Dirt": .display,
    "Rubik Distressed": .display,
    "Rubik Doodle Shadow": .display,
    "Rubik Doodle Triangles": .display,
    "Rubik Gemstones": .display,
    "Rubik Glitch": .display,
    "Rubik Glitch Pop": .display,
    "Rubik Iso": .display,
    "Rubik Lines": .display,
    "Rubik Maps": .display,
    "Rubik Marker Hatch": .display,
    "Rubik Maze": .display,
    "Rubik Microbe": .display,
    "Rubik Mono One": .sans,
    "Rubik Moonrocks": .display,
    "Rubik Pixels": .display,
    "Rubik Puddles": .display,
    "Rubik Scribble": .display,
    "Rubik Spray Paint": .display,
    "Rubik Storm": .display,
    "Rubik Vinyl": .display,
    "Rubik Wet Paint": .display,
    "Ruda": .sans,
    "Rufina": .serif,
    "Ruge Boogie": .script,
    "Ruluko": .sans,
    "Rum Raisin": .sans,
    "Ruslan Display": .display,
    "Russo One": .sans,
    "Ruthie": .script,
    "Ruwudu": .serif,
    "Rye": .display,
    "SN Pro": .sans,
    "STIX Two Math": .serif,
    "STIX Two Text": .serif,
    "SUSE": .sans,
    "SUSE Mono": .sans,
    "Sacramento": .script,
    "Sahitya": .serif,
    "Sail": .display,
    "Saira": .sans,
    "Saira Condensed": .sans,
    "Saira Extra Condensed": .sans,
    "Saira Semi Condensed": .sans,
    "Saira Stencil": .display,
    "Salsa": .display,
    "Sanchez": .serif,
    "Sancreek": .display,
    "Sankofa Display": .sans,
    "Sansation": .sans,
    "Sansita": .sans,
    "Sansita Swashed": .display,
    "Sarabun": .sans,
    "Sarala": .sans,
    "Sarina": .display,
    "Sarpanch": .sans,
    "Sassy Frass": .script,
    "Satisfy": .script,
    "Savate": .sans,
    "Sawarabi Gothic": .sans,
    "Sawarabi Mincho": .serif,
    "Scada": .sans,
    "Scheherazade New": .serif,
    "Schibsted Grotesk": .sans,
    "Schoolbell": .script,
    "Science Gothic": .sans,
    "Scope One": .serif,
    "Scoutie Sans": .sans,
    "Seaweed Script": .display,
    "Secular One": .sans,
    "Sedan": .serif,
    "Sedan SC": .serif,
    "Sedgwick Ave": .script,
    "Sedgwick Ave Display": .script,
    "Sekuya": .display,
    "Sen": .sans,
    "Send Flowers": .script,
    "Sevillana": .display,
    "Seymour One": .sans,
    "Shadows Into Light": .script,
    "Shadows Into Light Two": .script,
    "Shafarik": .display,
    "Shalimar": .script,
    "Shantell Sans": .display,
    "Shanti": .sans,
    "Share": .sans,
    "Share Tech": .sans,
    "Share Tech Mono": .mono,
    "Shippori Antique": .sans,
    "Shippori Antique B1": .sans,
    "Shippori Mincho": .serif,
    "Shippori Mincho B1": .serif,
    "Shizuru": .display,
    "Shojumaru": .display,
    "Short Stack": .script,
    "Shrikhand": .display,
    "Siemreap": .sans,
    "Sigmar": .display,
    "Sigmar One": .display,
    "Signika": .sans,
    "Signika Negative": .sans,
    "Silkscreen": .display,
    "Simonetta": .display,
    "Single Day": .display,
    "Sintony": .sans,
    "Sirin Stencil": .display,
    "Sirivennela": .sans,
    "Six Caps": .sans,
    "Sixtyfour": .mono,
    "Sixtyfour Convergence": .mono,
    "Skranji": .display,
    "Slabo 13px": .serif,
    "Slabo 27px": .serif,
    "Slackey": .display,
    "Slackside One": .script,
    "Smokum": .display,
    "Smooch": .script,
    "Smooch Sans": .sans,
    "Smythe": .display,
    "Sniglet": .display,
    "Snippet": .sans,
    "Snowburst One": .display,
    "Sofadi One": .display,
    "Sofia": .script,
    "Sofia Sans": .sans,
    "Sofia Sans Condensed": .sans,
    "Sofia Sans Extra Condensed": .sans,
    "Sofia Sans Semi Condensed": .sans,
    "Solitreo": .script,
    "Solway": .serif,
    "Sometype Mono": .mono,
    "Song Myung": .serif,
    "Sono": .sans,
    "Sonsie One": .display,
    "Sora": .sans,
    "Sorts Mill Goudy": .serif,
    "Sour Gummy": .sans,
    "Source Code Pro": .mono,
    "Source Sans 3": .sans,
    "Source Serif 4": .serif,
    "Space Grotesk": .sans,
    "Space Mono": .mono,
    "Special Elite": .display,
    "Special Gothic": .sans,
    "Special Gothic Condensed One": .sans,
    "Special Gothic Expanded One": .sans,
    "Spectral": .serif,
    "Spectral SC": .serif,
    "Spicy Rice": .display,
    "Spinnaker": .sans,
    "Spirax": .display,
    "Splash": .script,
    "Spline Sans": .sans,
    "Spline Sans Mono": .mono,
    "Squada One": .display,
    "Square Peg": .script,
    "Sree Krushnadevaraya": .serif,
    "Sriracha": .script,
    "Srisakdi": .display,
    "Staatliches": .display,
    "Stack Sans Headline": .sans,
    "Stack Sans Notch": .sans,
    "Stack Sans Text": .sans,
    "Stalemate": .script,
    "Stalinist One": .display,
    "Stardos Stencil": .display,
    "Stick": .sans,
    "Stick No Bills": .sans,
    "Stint Ultra Condensed": .serif,
    "Stint Ultra Expanded": .serif,
    "Stoke": .serif,
    "Story Script": .sans,
    "Strait": .sans,
    "Strichpunkt Sans": .sans,
    "Style Script": .script,
    "Stylish": .sans,
    "Sue Ellen Francisco": .script,
    "Suez One": .serif,
    "Sulphur Point": .sans,
    "Sumana": .serif,
    "Sunflower": .sans,
    "Sunshiney": .script,
    "Supermercado One": .display,
    "Sura": .serif,
    "Suranna": .serif,
    "Suravaram": .serif,
    "Suwannaphum": .serif,
    "Swanky and Moo Moo": .script,
    "Syncopate": .sans,
    "Syne": .sans,
    "Syne Mono": .mono,
    "Syne Tactile": .display,
    "TASA Explorer": .sans,
    "TASA Orbiter": .sans,
    "Tac One": .sans,
    "Tagesschrift": .display,
    "Tai Heritage Pro": .serif,
    "Tajawal": .sans,
    "Tangerine": .script,
    "Tapestry": .script,
    "Taprom": .display,
    "Tauri": .sans,
    "Taviraj": .serif,
    "Teachers": .sans,
    "Teko": .sans,
    "Tektur": .display,
    "Telex": .sans,
    "Tenali Ramakrishna": .sans,
    "Tenor Sans": .sans,
    "Text Me One": .sans,
    "Texturina": .serif,
    "Thasadith": .sans,
    "The Girl Next Door": .script,
    "The Nautigal": .script,
    "Tienne": .serif,
    "TikTok Sans": .sans,
    "Tillana": .display,
    "Tilt Neon": .display,
    "Tilt Prism": .display,
    "Tilt Warp": .display,
    "Timmana": .sans,
    "Tinos": .serif,
    "Tiny5": .sans,
    "Tiro Bangla": .serif,
    "Tiro Devanagari Hindi": .serif,
    "Tiro Devanagari Marathi": .serif,
    "Tiro Devanagari Sanskrit": .serif,
    "Tiro Gurmukhi": .serif,
    "Tiro Kannada": .serif,
    "Tiro Tamil": .serif,
    "Tiro Telugu": .serif,
    "Tirra": .sans,
    "Titan One": .display,
    "Titillium Web": .sans,
    "Tomorrow": .sans,
    "Tourney": .display,
    "Trade Winds": .display,
    "Train One": .display,
    "Triodion": .display,
    "Trirong": .serif,
    "Trispace": .sans,
    "Trocchi": .serif,
    "Trochut": .display,
    "Truculenta": .sans,
    "Trykker": .serif,
    "Tsukimi Rounded": .sans,
    "Tuffy": .sans,
    "Tulpen One": .display,
    "Turret Road": .display,
    "Twinkle Star": .script,
    "Ubuntu": .sans,
    "Ubuntu Condensed": .sans,
    "Ubuntu Mono": .mono,
    "Ubuntu Sans": .sans,
    "Ubuntu Sans Mono": .mono,
    "Uchen": .serif,
    "Ultra": .serif,
    "Unbounded": .sans,
    "Uncial Antiqua": .display,
    "Underdog": .display,
    "Unica One": .display,
    "UnifrakturCook": .display,
    "UnifrakturMaguntia": .display,
    "Unkempt": .display,
    "Unlock": .display,
    "Unna": .serif,
    "UoqMunThenKhung": .serif,
    "Updock": .script,
    "Urbanist": .sans,
    "VT323": .mono,
    "Valley Sans": .sans,
    "Vampiro One": .display,
    "Varela": .sans,
    "Varela Round": .sans,
    "Varta": .sans,
    "Vast Shadow": .serif,
    "Vazirmatn": .sans,
    "Vend Sans": .sans,
    "Vesper Libre": .serif,
    "Viaoda Libre": .display,
    "Vibes": .display,
    "Vibur": .script,
    "Victor Mono": .mono,
    "Vidaloka": .serif,
    "Viga": .sans,
    "Vina Sans": .display,
    "Voces": .sans,
    "Volkhov": .serif,
    "Vollkorn": .serif,
    "Vollkorn SC": .serif,
    "Voltaire": .sans,
    "Vujahday Script": .script,
    "WDXL Lubrifont JP N": .sans,
    "WDXL Lubrifont SC": .sans,
    "WDXL Lubrifont TC": .sans,
    "Waiting for the Sunrise": .script,
    "Wallpoet": .display,
    "Walter Turncoat": .script,
    "Warnes": .display,
    "Water Brush": .script,
    "Waterfall": .script,
    "Wavefont": .display,
    "Wellfleet": .serif,
    "Wendy One": .sans,
    "Whisper": .script,
    "WindSong": .script,
    "Winky Rough": .sans,
    "Winky Sans": .sans,
    "Wire One": .sans,
    "Wittgenstein": .serif,
    "Wix Madefor Display": .sans,
    "Wix Madefor Text": .sans,
    "Work Sans": .sans,
    "Workbench": .mono,
    "Xanh Mono": .mono,
    "Yaldevi": .sans,
    "Yanone Kaffeesatz": .sans,
    "Yantramanav": .sans,
    "Yarndings 12": .display,
    "Yarndings 12 Charted": .display,
    "Yarndings 20": .display,
    "Yarndings 20 Charted": .display,
    "Yatra One": .display,
    "Yellowtail": .script,
    "Yeon Sung": .display,
    "Yeseva One": .display,
    "Yesteryear": .script,
    "Yomogi": .script,
    "Young Serif": .serif,
    "Yrsa": .serif,
    "Ysabeau": .sans,
    "Ysabeau Infant": .sans,
    "Ysabeau Office": .sans,
    "Ysabeau SC": .sans,
    "Yuji Boku": .serif,
    "Yuji Hentaigana Akari": .script,
    "Yuji Hentaigana Akebono": .script,
    "Yuji Mai": .serif,
    "Yuji Syuku": .serif,
    "Yusei Magic": .sans,
    "Yuyu": .script,
    "Yuyu Short": .script,
    "ZCOOL KuaiLe": .sans,
    "ZCOOL QingKe HuangYou": .sans,
    "ZCOOL XiaoWei": .sans,
    "Zain": .sans,
    "Zalando Sans": .sans,
    "Zalando Sans Expanded": .sans,
    "Zalando Sans SemiExpanded": .sans,
    "Zen Antique": .serif,
    "Zen Antique Soft": .serif,
    "Zen Dots": .display,
    "Zen Kaku Gothic Antique": .sans,
    "Zen Kaku Gothic New": .sans,
    "Zen Kurenaido": .sans,
    "Zen Loop": .display,
    "Zen Maru Gothic": .sans,
    "Zen Old Mincho": .serif,
    "Zen Tokyo Zoo": .display,
    "Zeyada": .script,
    "Zhi Mang Xing": .script,
    "Zilla Slab": .serif,
    "Zilla Slab Highlight": .serif,
]
